<a href="https://colab.research.google.com/github/ofrajat/AD-Python/blob/master/NUMPY_DAY1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np


In [0]:
a=np.array([2,7,1,99,4])
b=np.array([12,17,11,199,14])
a+b

In [0]:
x=np.array([[2,3,5],[3,5,7]])
z=np.array([[2,6],[3,5],[4,2],[3,6]])
x

array([[2, 3, 5],
       [3, 5, 7]])

In [0]:
x[0][1]*2

6

will exclude range last no

In [0]:
x[0:1] 

array([[2, 3, 5]])

In [0]:
x[0:,0]   #to access column

array([2, 3])

In [0]:
x[0:,[0,2]]    #to access random column

array([[2, 5],
       [3, 7]])

In [0]:
z[[0,3],1]    #to access random element

array([6, 6])

In [0]:
d=np.array([[1,9,7],[3,2,8],[4,5,6],[2,9,0]])
d

array([[1, 9, 7],
       [3, 2, 8],
       [4, 5, 6],
       [2, 9, 0]])

In [0]:

d[1:3,1]

array([2, 5])

In [0]:
d[1:4,2]

array([8, 6, 0])

In [0]:
d[[3],2]

array([0])

In [0]:
d[1:4,[0,2]]

array([[3, 8],
       [4, 6],
       [2, 0]])

In [0]:
x.reshape(3,2)  #to change dimensions

array([[2, 3],
       [5, 3],
       [5, 7]])

In [0]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])